# Workflow to publish a new release version of the SDK to Github Packages
name: Publish Release SDK (GitHub Packages)

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write # publish to GitHub Packages

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      #  Write a temporary .npmrc with auth for GitHub Packages
      - name: Configure npm for GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          scope: '@benji-money'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # OPTIONAL AUTH CHECK: Debug authentication
      - name: Check authentication (optional debug)
        run: npm whoami --registry=https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Publish Stable Release to GitHub Packages with the 'latest' dist-tag, using the version in package.json
      - name: Publish to GitHub Packages 
        run: npm publish --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}